export { default as Home } from './Home.jsx'
export { default as About } from './About.jsx'
export { default as Services } from './Services.jsx'
export { default as Contact } from './Contact.jsx'
export { default as OurWork } from './OurWork.jsx'
export { default as SetUp } from './SetUp.jsx'
export { default as Token } from './Token.jsx'